
server:
  port: 8080
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

backup:
  folder: E:\RHS-Git\rhs-poc\spring-kafka\BackupNew\
  extension: .txt

amazonProperties:
  endpointUrl: http://s3.console.aws.amazon.com/
  accessKey: AKIAZSZRA3KGDOVY4ZKI
  secretKey: Xo5+tQGj25UmlFSOmGNaNXpJTKRv7XnS6RbPok/a
  bucketName: sample-rhs-bucket
  downloadpath: E:\RHS-Git\rhs-poc\spring-kafka\S3-Files
  downloadextension: txt

?SSL: false