spring:
   cloud:
      stream:
         bindings:
            process-in-0:
               destination: cardservices
            process-out-0:
               destination: banksolutions
#            output-in-0:
#               destination: banksolutions
         kafka:
            streams:
               binder:
                  appplicationId: demostreams
                  brokers: localhost:8092
